/* SG Farms Internationalization (i18n) Translations */

const TRANSLATIONS = {
  en: {
    nav_home: "Home",
    nav_shop: "Shop Crops",
    nav_logs: "Our Field Logs",
    nav_blog: "Farming Tips",
    hero_title: "Fresh Crops Directly From Farms To Your Home",
    hero_subtitle: "Cultivated with 100% organic methods in the fertile fields of Mukkollu, Andhra Pradesh.",
    btn_shop: "Shop Fresh Crops",
    btn_explore: "Explore Farm Logs",
    why_title: "Why Choose SG Farms?",
    why_desc: "We bring agricultural excellence and chemical-free nutrition to urban doorsteps.",
    why_1_title: "100% Organic certified",
    why_1_desc: "Nourished with Panchagavya compost, completely pesticide-free.",
    why_2_title: "Direct Farm Delivery",
    why_2_desc: "Harvested at dawn and delivered in Andhra Pradesh within 48 hours.",
    why_3_title: "Support Local Farmers",
    why_3_desc: "Fair trade that cuts out middle-men, empowering rural families.",
    featured_crops: "Featured Fresh Crops",
    featured_crops_desc: "Naturally harvested this season. Rich in flavor and nutrients.",
    btn_add_cart: "Add to Cart",
    btn_buy_now: "Buy Now",
    search_placeholder: "Search crops, vegetables or fruits...",
    filter_category: "Categories",
    filter_all: "All Produce",
    filter_fruits: "Fresh Fruits",
    filter_veggies: "Vegetables",
    filter_grains: "Grains",
    filter_herbs: "Herbs & Spices",
    sort_by: "Sort By",
    sort_featured: "Featured First",
    sort_price_low: "Price: Low to High",
    sort_price_high: "Price: High to Low",
    price_tag: "Price",
    stock_available: "Available Stock",
    organic_badge: "Organic",
    regular_badge: "Regular",
    booking_title: "Book a Farm Experience",
    booking_subtitle: "Visit our Mukkollu fields, attend traditional agriculture workshops, and taste fresh organic meals.",
    visit_form_name: "Your Full Name",
    visit_form_date: "Preferred Visit Date",
    visit_form_guests: "Number of Guests",
    visit_form_phone: "Mobile Number (+91)",
    visit_form_workshop: "Select Workshop Activity",
    visit_form_workshop_none: "General Farm Tour & Fruit Picking",
    visit_form_workshop_compost: "Organic Compost Prep Workshop",
    visit_form_workshop_pest: "Natural Pest Repellent (Neem) Workshop",
    btn_book_visit: "Schedule Farm Visit",
    booking_success: "Farm visit scheduled successfully! We will contact you shortly.",
    whatsapp_chat: "Talk to Farmer",
    whatsapp_order: "Order on WhatsApp",
    chatbot_welcome: "Namaste! Welcome to SG Farms. I am your Agricultural Assistant. How can I help you today? You can ask about our organic crops, farm visits, delivery system, or cooking tips!",
    chatbot_suggest_1: "Are mangoes organic?",
    chatbot_suggest_2: "Book a farm visit",
    chatbot_suggest_3: "Where is Mukkollu?",
    chatbot_suggest_4: "What is Panchagavya?",
    weather_widget_title: "Live Mukkollu Field Weather",
    recommendation_title: "AI Crop Recommendations For You",
    recommendation_desc: "Based on summer season and local availability, we recommend trying our freshly harvested mangoes and cooling papayas.",
    cart_empty: "Your shopping cart is empty.",
    cart_title: "Shopping Cart",
    cart_checkout: "Proceed to Checkout",
    review_title: "Customer Reviews",
    review_add: "Write a Review",
    review_name: "Your Name",
    review_comment: "Review Comment",
    review_rating: "Rating",
    review_submit: "Submit Review"
  },
  te: {
    nav_home: "ఇల్లు",
    nav_shop: "పంటలు",
    nav_logs: "పొలం వివరాలు",
    nav_blog: "వ్యవసాయ చిట్కాలు",
    hero_title: "పొలాల నుండి నేరుగా మీ ఇంటికి తాజా పంటలు",
    hero_subtitle: "ఆంధ్రప్రదేశ్, ముక్కొల్లు సారవంతమైన పొలాలలో 100% సేంద్రీయ పద్ధతిలో పండించిన పంటలు.",
    btn_shop: "తాజా పంటలను కొనండి",
    btn_explore: "పొలం రికార్డులు చూడండి",
    why_title: "SG ఫార్మ్స్ ఎందుకు?",
    why_desc: "మేము రసాయనాలు లేని పౌష్టికాహారాన్ని నేరుగా మీ ఇంటి ముందుకు తీసుకువస్తాము.",
    why_1_title: "100% సేంద్రీయ ధృవీకరణ",
    why_1_desc: "పంచగవ్యతో పెంచబడినవి, పురుగుమందులు పూర్తిగా లేవు.",
    why_2_title: "నేరుగా పొలం నుండి సరఫరా",
    why_2_desc: "ఉదయాన్నే కోసి 48 గంటలలోపు ఆంధ్రప్రదేశ్‌లో పంపిణీ చేయబడుతుంది.",
    why_3_title: "స్థానిక రైతులకు మద్దతు",
    why_3_desc: "దళారీలు లేని వ్యాపారం, గ్రామీణ కుటుంబాల ఆర్థిక సాధికారత.",
    featured_crops: "ఈ సీజన్ తాజా పంటలు",
    featured_crops_desc: "సహజంగా పండిన పంటలు. అద్భుతమైన రుచి, పోషకాలతో నిండినవి.",
    btn_add_cart: "కార్ట్‌కు చేర్చు",
    btn_buy_now: "ఇప్పుడే కొనండి",
    search_placeholder: "పంటలు, కూరగాయలు లేదా పండ్లను వెతకండి...",
    filter_category: "విభాగాలు",
    filter_all: "అన్ని రకాలు",
    filter_fruits: "తాజా పండ్లు",
    filter_veggies: "కూరగాయలు",
    filter_grains: "ధాన్యాలు",
    filter_herbs: "మూలికలు & మసాలాలు",
    sort_by: "క్రమబద్ధీకరించు",
    sort_featured: "ముందుగా ప్రాచుర్యం పొందినవి",
    sort_price_low: "ధర: తక్కువ నుండి ఎక్కువ",
    sort_price_high: "ధర: ఎక్కువ నుండి తక్కువ",
    price_tag: "ధర",
    stock_available: "అందుబాటులో ఉన్న నిల్వ",
    organic_badge: "సేంద్రీయ (Organic)",
    regular_badge: "సాధారణ (Regular)",
    booking_title: "పొలం సందర్శన బుకింగ్",
    booking_subtitle: "ముక్కొల్లులోని మా పొలాలను సందర్శించండి, వ్యవసాయ వర్క్‌షాప్‌లలో పాల్గొనండి మరియు తాజా భోజనాన్ని రుచి చూడండి.",
    visit_form_name: "మీ పూర్తి పేరు",
    visit_form_date: "సందర్శించదలచిన తేదీ",
    visit_form_guests: "సందర్శకుల సంఖ్య",
    visit_form_phone: "మొబైల్ సంఖ్య (+91)",
    visit_form_workshop: "వర్క్‌షాప్ కార్యాచరణ ఎంచుకోండి",
    visit_form_workshop_none: "పొలం పర్యటన & పండ్లు కోయడం",
    visit_form_workshop_compost: "సేంద్రీయ ఎరువుల తయారీ వర్క్‌షాప్",
    visit_form_workshop_pest: "వేప పురుగుమందు తయారీ వర్క్‌షాప్",
    btn_book_visit: "సందర్శన షెడ్యూల్ చేయండి",
    booking_success: "పొలం సందర్శన విజయవంతంగా బుక్ చేయబడింది! మేము త్వరలో మిమ్మల్ని సంప్రదిస్తాము.",
    whatsapp_chat: "రైతుతో మాట్లాడండి",
    whatsapp_order: "వాట్సాప్‌లో ఆర్డర్ చేయండి",
    chatbot_welcome: "నమస్తే! SG ఫార్మ్స్‌కు స్వాగతం. నేను మీ వ్యవసాయ సహాయకుడిని. ఈ రోజు మీకు ఎలా సహాయపడగలను? మా ఆర్గానిక్ పంటలు, పొలం సందర్శనలు లేదా డెలివరీ గురించి నన్ను అడగవచ్చు!",
    chatbot_suggest_1: "మామిడి పండ్లు ఆర్గానిక్ నా?",
    chatbot_suggest_2: "పొలాన్ని ఎలా సందర్శించాలి?",
    chatbot_suggest_3: "ముక్కొల్లు ఎక్కడ ఉంది?",
    chatbot_suggest_4: "పంచగవ్య అంటే ఏమిటి?",
    weather_widget_title: "ముక్కొల్లు వాతావరణం",
    recommendation_title: "మీ కొరకు వ్యవసాయ సిఫార్సులు",
    recommendation_desc: "ఈ వేసవి కాలం వాతావరణానికి అనుకూలంగా, ముక్కొల్లు మామిడిపండ్లు మరియు పప్పాయలను రుచి చూడాల్సిందిగా సిఫార్సు చేస్తున్నాము.",
    cart_empty: "మీ కార్ట్ ఖాళీగా ఉంది.",
    cart_title: "షాపింగ్ కార్ట్",
    cart_checkout: "చెక్అవుట్ చేయండి",
    review_title: "వినియోగదారుల సమీక్షలు",
    review_add: "సమీక్ష వ్రాయండి",
    review_name: "మీ పేరు",
    review_comment: "అభిప్రాయం",
    review_rating: "రేటింగ్",
    review_submit: "సమీక్షను సమర్పించండి"
  },
  hi: {
    nav_home: "मुख्य पृष्ठ",
    nav_shop: "फसलें खरीदें",
    nav_logs: "खेत की जानकारी",
    nav_blog: "खेती के टिप्स",
    hero_title: "खेतों से सीधे आपके घर तक ताज़ा फसलें",
    hero_subtitle: "आंध्र प्रदेश के मुक्कोल्लू के उपजाऊ खेतों में 100% जैविक तरीकों से उगाई गई फसलें।",
    btn_shop: "ताज़ा फसलें खरीदें",
    btn_explore: "खेत के रिकॉर्ड देखें",
    why_title: "एसजी फार्म्स क्यों चुनें?",
    why_desc: "हम आपके दरवाजे पर बिना रसायनों के पौष्टिक उत्पाद पहुंचाते हैं।",
    why_1_title: "100% जैविक प्रमाणित",
    why_1_desc: "पंचगव्य खाद से तैयार, कीटनाशकों से पूरी तरह मुक्त।",
    why_2_title: "खेत से सीधी डिलीवरी",
    why_2_desc: "सुबह कटाई और 48 घंटे के भीतर आंध्र प्रदेश में डिलीवरी।",
    why_3_title: "स्थानीय किसानों का समर्थन",
    why_3_desc: "बिचौलियों के बिना व्यापार, जिससे ग्रामीण परिवारों को लाभ मिले।",
    featured_crops: "इस सीजन की ताज़ा फसलें",
    featured_crops_desc: "प्राकृतिक रूप से उगाई गई फसलें। स्वाद और पोषक तत्वों से भरपूर।",
    btn_add_cart: "कार्ट में जोड़ें",
    btn_buy_now: "अभी खरीदें",
    search_placeholder: "फसलों, सब्जियों या फलों को खोजें...",
    filter_category: "श्रेणियाँ",
    filter_all: "सभी उत्पाद",
    filter_fruits: "ताज़ा फल",
    filter_veggies: "सब्जियाँ",
    filter_grains: "अनाज",
    filter_herbs: "जड़ी-बूटियाँ और मसाले",
    sort_by: "क्रमबद्ध करें",
    sort_featured: "लोकप्रिय पहले",
    sort_price_low: "कीमत: कम से अधिक",
    sort_price_high: "कीमत: अधिक से कम",
    price_tag: "कीमत",
    stock_available: "उपलब्ध स्टॉक",
    organic_badge: "ऑर्गेनिक",
    regular_badge: "सामान्य",
    booking_title: "खेत की यात्रा बुक करें",
    booking_subtitle: "मुक्कोल्लू में हमारे खेतों का दौरा करें, जैविक खेती कार्यशालाओं में भाग लें और ताज़ा भोजन का आनंद लें।",
    visit_form_name: "आपका पूरा नाम",
    visit_form_date: "यात्रा की तिथि",
    visit_form_guests: "मेहमानों की संख्या",
    visit_form_phone: "मोबाइल नंबर (+91)",
    visit_form_workshop: "कार्यशाला गतिविधि चुनें",
    visit_form_workshop_none: "फार्म टूर और फल तोड़ना",
    visit_form_workshop_compost: "जैविक खाद निर्माण कार्यशाला",
    visit_form_workshop_pest: "प्राकृतिक नीम कीटनाशक कार्यशाला",
    btn_book_visit: "यात्रा का समय तय करें",
    booking_success: "फार्म यात्रा का समय सफलतापूर्वक बुक हो गया है! हम जल्द ही आपसे संपर्क करेंगे।",
    whatsapp_chat: "किसान से बात करें",
    whatsapp_order: "व्हाट्सएप पर ऑर्डर करें",
    chatbot_welcome: "नमस्ते! एसजी फार्म्स में आपका स्वागत है। मैं आपका कृषि सहायक हूँ। आज मैं आपकी क्या मदद कर सकता हूँ? आप फसलों, खेत की यात्रा या डिलीवरी के बारे में पूछ सकते हैं।",
    chatbot_suggest_1: "क्या आम ऑर्गेनिक हैं?",
    chatbot_suggest_2: "खेत की यात्रा बुक करें",
    chatbot_suggest_3: "मुक्कोल्लू कहाँ है?",
    chatbot_suggest_4: "पंचगव्य क्या है?",
    weather_widget_title: "मुक्कोल्लू मौसम अपडेट",
    recommendation_title: "आपके लिए एआई फसल सुझाव",
    recommendation_desc: "गर्मी के मौसम के आधार पर, हम आपको हमारे ताज़ा मीठे आम और सेहतमंद पपीता आजमाने का सुझाव देते हैं।",
    cart_empty: "आपकी कार्ट खाली है।",
    cart_title: "शॉपिंग कार्ट",
    cart_checkout: "चेकआउट की ओर बढ़ें",
    review_title: "ग्राहक समीक्षाएं",
    review_add: "समीक्षा लिखें",
    review_name: "आपका नाम",
    review_comment: "अपनी राय लिखें",
    review_rating: "रेटिंग",
    review_submit: "समीक्षा भेजें"
  }
};

export const i18n = {
  t(key, lang = 'en') {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS['en'];
    return dict[key] || TRANSLATIONS['en'][key] || key;
  }
};
